# -*- coding: utf-8 -*-
"""The_Full_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rSPPgkBZfZXRqziXK0wcSC--CLDqUKjR
"""

"""# Step 1: Data Acquisition
(get 36h data from the current time, of harpnums that are active)

"""

import drms
import pandas as pd
from datetime import datetime, timedelta, timezone
import os
import json

STATUS_FILE = "pipeline_status.json"

def update_status(status, progress, message):
    try:
        with open(STATUS_FILE, "w") as f:
            json.dump({"status": status, "progress": progress, "message": message}, f)
    except Exception:
        pass

# Configuration
EMAIL = "saiprasad.jamdar17561@sakec.ac.in"
SEGMENTS = ["Br", "Bt", "Bp"]
# DYNAMIC CONFIG: Read from environment (passed by the backend router)
HISTORY_HOURS = int(os.environ.get('HISTORY_HOURS', 36))
CADENCE_MINS = 12
EXPECTED_FRAMES = int((HISTORY_HOURS * 60) / CADENCE_MINS)
MISSING_DATA_TOLERANCE = 0.90
DOWNLOAD_DIR = "./live_inference_data"

def run_acquisition(target_harp=None, target_time_str=None):
    """
    If target_harp and target_time_str are None, runs LIVE mode.
    Otherwise, runs TARGETED historical mode.
    """
    update_status("running", 5, "Connecting to Stanford JSOC (drms)...")
    client = drms.Client(email=EMAIL)
    os.makedirs(DOWNLOAD_DIR, exist_ok=True)

    # 1. Determine Series and Time Window
    if target_harp and target_time_str:
        # TARGETED MODE
        series = "hmi.sharp_cea_720s" # Definitive archive
        t_end = datetime.strptime(target_time_str, "%Y-%m-%d %H:%M:%S")
        active_harps = [target_harp]
        print(f"--- MODE: TARGETED (HARP {target_harp} @ {target_time_str}) ---")
    else:
        # LIVE MODE
        series = "hmi.sharp_cea_720s_nrt" # Near Real-Time
        now = datetime.now(timezone.utc)
        t_end = now - timedelta(hours=3) # Account for NRT latency

        t_end_query_str = t_end.strftime("%Y.%m.%d_%H:%M_TAI")
        t_probe = (t_end - timedelta(minutes=CADENCE_MINS)).strftime("%Y.%m.%d_%H:%M_TAI")
        probe_query = f"{series}[][{t_probe}-{t_end_query_str}]"

        print(f"--- MODE: LIVE (Polling currently active regions) ---")
        try:
            keys = client.query(probe_query, key="HARPNUM")
            if keys is None or keys.empty:
                print("No active HARPNUMs found in the operational window.")
                return
            active_harps = keys['HARPNUM'].unique()
        except Exception as e:
            print(f"Query failure: {e}")
            return

    t_start = t_end - timedelta(hours=HISTORY_HOURS)
    t_end_str = t_end.strftime("%Y.%m.%d_%H:%M_TAI")
    t_start_str = t_start.strftime("%Y.%m.%d_%H:%M_TAI")

    # 2. Validate Coverage and Download
    valid_harps = []
    for i, harp in enumerate(active_harps):
        update_status("running", 10 + int((i / len(active_harps)) * 20), f"Validating coverage for AR {harp}...")
        history_query = f"{series}[{harp}][{t_start_str}-{t_end_str}]"
        try:
            hist_keys = client.query(history_query, key="T_REC")
            actual_frames = len(hist_keys) if hist_keys is not None else 0

            if actual_frames >= (EXPECTED_FRAMES * MISSING_DATA_TOLERANCE):
                valid_harps.append(harp)
                print(f"HARP {harp}: Validated ({actual_frames} frames).")
            else:
                print(f"HARP {harp}: Skipped (Only {actual_frames} frames found).")
        except Exception:
            continue

    # 3. Export and Download
    for idx, harp in enumerate(valid_harps):
        harp_dir = os.path.join(DOWNLOAD_DIR, str(harp))
        # SMART CACHING: Do NOT delete the whole folder. 
        # Only delete files that have "expired" (older than t_start)
        os.makedirs(harp_dir, exist_ok=True)
        if os.path.exists(harp_dir):
            cleaned_count = 0
            for f in os.listdir(harp_dir):
                if f.endswith(".fits"):
                    try:
                        # Filename example: hmi.sharp_cea_720s_nrt.13467.20260429_232400_TAI.Bp.fits
                        # Timestamp is the 4th dot-separated part
                        ts_part = f.split('.')[3] # "20260429_232400_TAI"
                        ts_str = ts_part.split('_')[0] + "_" + ts_part.split('_')[1] # "20260429_232400"
                        file_dt = datetime.strptime(ts_str, "%Y%m%d_%H%M%S").replace(tzinfo=timezone.utc)
                        
                        # If the file is older than our current 36h window start, delete it
                        if file_dt < t_start:
                            os.remove(os.path.join(harp_dir, f))
                            cleaned_count += 1
                    except Exception:
                        continue
            if cleaned_count > 0:
                print(f"[Cache] Cleaned up {cleaned_count} expired FITS files for HARP {harp}")

        export_query = f"{series}[{harp}][{t_start_str}-{t_end_str}]{{{','.join(SEGMENTS)}}}"
        print(f"Requesting export manifest for {harp}...")
        update_status("running", 30 + int((idx / max(1, len(valid_harps))) * 40), f"Downloading {HISTORY_HOURS}h magnetograms for AR {harp}...")
        try:
            import requests as _requests
            from concurrent.futures import ThreadPoolExecutor, as_completed
            import time

            # Retry loop to handle JSOC's 1-concurrent-request-per-user limit (status=7)
            max_retries = 15
            for attempt in range(max_retries):
                try:
                    request = client.export(export_query, method='url', protocol='fits')
                    
                    # Block until JSOC has finished staging the files on their end
                    print(f"  Waiting for JSOC export to stage (this can take a minute)...")
                    request.wait()

                    # Get the full list of file URLs from the export manifest
                    file_list = request.urls  # DataFrame with 'url' and 'record'
                    break  # Success!
                except Exception as e:
                    err_str = str(e)
                    if "[status=7]" in err_str or "pending export requests" in err_str:
                        print(f"  JSOC queue is full (status=7). Waiting 30s before retry {attempt+1}/{max_retries}...")
                        update_status("running", 30 + int((idx / max(1, len(valid_harps))) * 40), f"Waiting for previous JSOC export to finish (retry {attempt+1})...")
                        time.sleep(30)
                    elif "10054" in err_str or "Connection" in err_str or "Timeout" in err_str:
                        print(f"  Network drop during JSOC poll: {err_str}. Retrying in 10s ({attempt+1}/{max_retries})...")
                        time.sleep(10)
                    else:
                        raise e
            else:
                raise Exception("JSOC queue timeout: too many pending requests for this email.")

            total = len(file_list)
            print(f"  {total} files to download for AR {harp}. Starting parallel download (10 threads)...")

            def download_one(row):
                url = row['url']
                # Depending on drms version, filename might be missing from urls property, so extract from url
                fname = os.path.basename(url)
                dest = os.path.join(harp_dir, fname)

                # SKIP if file already exists (Smart Cache)
                if os.path.exists(dest) and os.path.getsize(dest) > 0:
                    return f"SKIP: {fname}"

                for dl_attempt in range(4):
                    try:
                        # Fail-fast timeout to prevent 8-minute hangs when JSOC drops connections silently
                        resp = _requests.get(url, timeout=15, stream=True)
                        resp.raise_for_status()
                        with open(dest, 'wb') as f_out:
                            for chunk in resp.iter_content(chunk_size=8192):
                                if chunk:
                                    f_out.write(chunk)
                        return f"OK: {fname}"
                    except Exception as dl_err:
                        if dl_attempt == 3:
                            return f"FAIL: {fname} ({dl_err})"
                        time.sleep(2 ** dl_attempt) # Exponential backoff: 1s, 2s, 4s

            downloaded, skipped, failed = 0, 0, 0
            with ThreadPoolExecutor(max_workers=10) as executor:
                futures = {executor.submit(download_one, row): i for i, row in file_list.iterrows()}
                for i, future in enumerate(as_completed(futures)):
                    result = future.result()
                    if result.startswith("OK"): downloaded += 1
                    elif result.startswith("SKIP"): skipped += 1
                    else: failed += 1; print(f"    {result}")
                    
                    # Print progress every 20 files
                    processed = downloaded + skipped + failed
                    if processed % 20 == 0 or processed == total:
                        print(f"    ... {processed}/{total} files processed ({downloaded} DL, {skipped} cache)")

            print(f"AR {harp} done: {downloaded} downloaded, {skipped} cached, {failed} failed.")
        except Exception as e:
            print(f"Error for AR {harp} (skipping): {e}")
            update_status("running", 30 + int((idx / max(1, len(valid_harps))) * 40), f"Skipped AR {harp}: {str(e)[:60]}")
            continue

if __name__ == "__main__":
    # To run LIVE:
    run_acquisition()

    # To run TARGETED (Uncomment below and comment out run_acquisition() above):
    # run_acquisition(target_harp=7115, target_time_str="2017-09-06 12:00:00")

"""# Step 2: Feature Extraction"""

import os
import glob
import numpy as np
import pandas as pd
from astropy.io import fits
from datetime import datetime, timezone
from skimage.measure import label, regionprops, euler_number
import warnings

warnings.filterwarnings("ignore")

# Configuration
INPUT_DIR = "./historical_test_data"
SEQUENCE_LENGTH = 60
CADENCE_MINS = 12.0

def get_solar_cycle_phase(date_str):
    try:
        dt = pd.to_datetime(date_str).to_pydatetime()
        c24_start, c24_end = datetime(2008, 12, 1), datetime(2019, 12, 1)
        c25_start, c25_end = datetime(2019, 12, 1), datetime(2030, 12, 1)
        if c24_start <= dt < c24_end:
            return float((dt - c24_start).total_seconds() / (c24_end - c24_start).total_seconds())
        elif dt >= c25_start:
            return float((dt - c25_start).total_seconds() / (c25_end - c25_start).total_seconds())
        return 0.5
    except:
        return 0.0

def parse_tai_string(t_str):
    try:
        parts = t_str.split('_')
        return datetime.strptime(parts[0] + "_" + parts[1], "%Y%m%d_%H%M%S")
    except (ValueError, IndexError):
        return None

def compute_potential_field_cea(br, dx, dy):
    ny, nx = br.shape
    if nx * ny == 0:
        return None, None
    kx = 2.0 * np.pi * np.fft.fftfreq(nx).reshape(1, -1) / dx
    ky = 2.0 * np.pi * np.fft.fftfreq(ny).reshape(-1, 1) / dy
    k = np.sqrt(kx**2 + ky**2)
    k[0, 0] = 1.0
    br_hat = np.fft.fft2(br)
    bx_pot = np.real(np.fft.ifft2(-1j * (kx / k) * br_hat))
    by_pot = np.real(np.fft.ifft2(-1j * (ky / k) * br_hat))
    return bx_pot, by_pot

def extract_hed_features_cea(br, bt, bp, scales):
    dx, dy, da = scales
    bx_obs = -bp
    by_obs = -bt
    bz_obs = br

    bx_pot, by_pot = compute_potential_field_cea(br, dx, dy)
    if bx_pot is None:
        return np.zeros(14), 0.0

    rho = ((bx_obs - bx_pot)**2 + (by_obs - by_pot)**2) / (8.0 * np.pi)

    mask = rho > 5000.0
    used_fallback = 0.0
    if np.sum(mask) < 10:
        mask = rho > np.percentile(rho, 99)
        used_fallback = 1.0

    bh_obs = np.sqrt(bx_obs**2 + by_obs**2)
    curl_z = np.gradient(by_obs, axis=1) / dx - np.gradient(bx_obs, axis=0) / dy
    curl_z_SI = curl_z * 100.0
    mu0_SI = 4.0 * np.pi * 1e-7
    jz_Am2 = (curl_z * 1e-2) / mu0_SI

    vec = np.zeros(14)
    m_sum = np.sum(mask)

    if m_sum > 0:
        vec[0] = np.sum(rho[mask]) * da
        vec[1] = np.sum(np.abs(bz_obs[mask])) * da
        vec[2] = np.sum(np.abs(jz_Am2[mask])) * da * 1e-4
        vec[3] = np.mean(np.abs(jz_Am2[mask]))

        hc_SI = bz_obs * curl_z_SI
        vec[4] = np.sum(np.abs(hc_SI[mask])) * da * 1e-4
        vec[5] = np.mean(np.abs(hc_SI[mask]))
        vec[6] = np.sum(hc_SI[mask]) * da * 1e-4

        sum_bz2 = np.sum(bz_obs[mask]**2)
        if sum_bz2 > 0:
            vec[7] = (np.sum(curl_z[mask] * bz_obs[mask]) / sum_bz2) * 1e8

        bh_pot = np.sqrt(bx_pot**2 + by_pot**2)
        dot_h = bx_obs * bx_pot + by_obs * by_pot
        mag_h = bh_obs * bh_pot
        shear_mask = mask & (bh_obs > 10.0)
        if np.sum(shear_mask) > 0:
            vec[8] = np.mean(np.arccos(np.clip(np.abs(dot_h[shear_mask]) / (mag_h[shear_mask] + 1e-6), 0.0, 1.0)))

        grad_bh_x = np.gradient(bh_obs, axis=1) / dx * 100.0
        grad_bh_y = np.gradient(bh_obs, axis=0) / dy * 100.0
        vec[9] = np.mean(np.sqrt(grad_bh_x**2 + grad_bh_y**2)[mask])
        vec[10] = m_sum * da

        lbl, n_islands = label(mask, connectivity=2, return_num=True)
        chi = euler_number(mask, connectivity=2)
        beta_0 = n_islands
        beta_1 = max(beta_0 - chi, 0)
        norm_area = vec[10] / 1e18
        if norm_area > 0.001:
            vec[12] = (beta_0 + beta_1) / norm_area

        vec[13] = used_fallback

    return vec, vec[6]

def build_file_map(local_folder_path):
    file_map = {}
    for f in glob.glob(os.path.join(local_folder_path, "*.fits")):
        base = os.path.basename(f)
        parts = base.split('.')
        if len(parts) >= 3 and 'TAI' in base:
            t_str, comp = parts[-3], parts[-2]
            file_map.setdefault(t_str, {})[comp] = f
    return file_map

def process_live_harp(harp_dir):
    file_map = build_file_map(harp_dir)
    raw_timestamps = sorted([ts for ts in file_map.keys() if parse_tai_string(ts) is not None])

    if not raw_timestamps:
        return None

    # Isolate the most recent timestamps required to fulfill the SEQUENCE_LENGTH
    # Assuming the data acquisition downloaded excess history (e.g., 180 frames).
    aligned_timestamps = []
    current_dt = parse_tai_string(raw_timestamps[-1])

    for i in range(SEQUENCE_LENGTH - 1, -1, -1):
        target_dt = current_dt - pd.Timedelta(minutes=CADENCE_MINS * i)
        # Find closest match within a 6-minute tolerance
        closest_ts = None
        min_diff = float('inf')
        for ts in raw_timestamps:
            dt = parse_tai_string(ts)
            diff = abs((dt - target_dt).total_seconds())
            if diff <= 360 and diff < min_diff:
                closest_ts = ts
                min_diff = diff
        aligned_timestamps.append(closest_ts)

    # Extract Static Features from the most recent valid frame
    valid_ts = [ts for ts in aligned_timestamps if ts is not None]
    if not valid_ts: return None

    ref_f = file_map[valid_ts[-1]].get('Br')
    if not ref_f: return None

    with fits.open(ref_f) as h:
        h0 = h[1].header #if len(h) > 1 else h[0].header
        rsun_cm = h0.get('RSUN_REF', 6.96e8) * 100.0
        dx = h0.get('CDELT1', 0.03) * (np.pi / 180.0) * rsun_cm
        dy, da = dx, dx * dx
        scales = (dx, dy, da)


            # h0      = h[1].header
            # rsun_cm = h0.get('RSUN_REF', 6.96e8) * 100.0
            # cdelt   = h0.get('CDELT1', 0.03)
            # dx      = cdelt * (np.pi / 180.0) * rsun_cm
            # dy      = dx
            # da      = dx * dy
            # scales  = (dx, dy, da)


        lon_rad = h0.get('CRVAL1', 0.0) * (np.pi / 180.0)
        lat_rad = h0.get('CRVAL2', 0.0) * (np.pi / 180.0)
        static_vec = [float(np.sin(lon_rad) * np.cos(lat_rad)), float(np.sin(lat_rad)), get_solar_cycle_phase(str(h0.get('DATE-OBS')))]

    history, h_buffer, mask_history = [], [], []

    for ts in aligned_timestamps:
        if ts is None or 'Br' not in file_map[ts] or 'Bt' not in file_map[ts] or 'Bp' not in file_map[ts]:
            # Impute missing frames (Forward Fill)
            if history:
                new_vec = history[-1].copy()
                new_vec[11] = 0.0
                history.append(new_vec)
                h_buffer.append(h_buffer[-1])
            else:
                history.append(np.zeros(14))
                h_buffer.append(0.0)
            mask_history.append(0.0)
            continue

        try:
            br = np.nan_to_num(fits.getdata(file_map[ts]['Br'], 1))
            bt = np.nan_to_num(fits.getdata(file_map[ts]['Bt'], 1))
            bp = np.nan_to_num(fits.getdata(file_map[ts]['Bp'], 1))

            vec, h_val = extract_hed_features_cea(br, bt, bp, scales)
            del br, bt, bp

            # Compute Jolt
            if len(h_buffer) >= 2 and mask_history[-1] == 1.0 and mask_history[-2] == 1.0:
                vec[11] = (h_val - 2 * h_buffer[-1] + h_buffer[-2]) / (720.0 ** 2)
            else:
                vec[11] = 0.0

            history.append(vec)
            h_buffer.append(h_val)
            mask_history.append(1.0)
        except Exception as e:
            print(f"Physics engine failure for {ts}: {e}")
            if history:
                history.append(history[-1].copy())
                h_buffer.append(h_buffer[-1])
            else:
                history.append(np.zeros(14))
                h_buffer.append(0.0)
            mask_history.append(0.0)

    X_seq = np.expand_dims(np.array(history, dtype=np.float32), axis=0)
    X_static = np.expand_dims(np.array(static_vec, dtype=np.float32), axis=0)
    X_mask = np.expand_dims(np.array(mask_history, dtype=np.float32).reshape(-1, 1), axis=0)


    return X_seq, X_static, X_mask
def run_extraction(target_harp=None):
    # DYNAMIC PATH: Always use the live download directory
    INPUT_DIR = DOWNLOAD_DIR
    if not os.path.exists(INPUT_DIR):
        os.makedirs(INPUT_DIR, exist_ok=True)
        
    inference_tensors = {}
    
    if target_harp:
        harps = [str(target_harp)]
    else:
        harps = [d for d in os.listdir(INPUT_DIR) if os.path.isdir(os.path.join(INPUT_DIR, d))]

    for i, harp in enumerate(harps):
        update_status("running", 70 + int((i / max(1, len(harps))) * 15), f"Extracting physical features for AR {harp}...")
        print(f"Extracting features for HARP {harp}...")
        result = process_live_harp(os.path.join(INPUT_DIR, harp))
        if result:
            X_seq, X_static, X_mask = result
            inference_tensors[harp] = result
            print(f"  HARP {harp} successful. Sequence shape: {X_seq.shape}")
        else:
            print(f"  HARP {harp} failed extraction.")

    return inference_tensors

if __name__ == "__main__":
    tensors = run_extraction()

"""# Step 3: Normalization"""

import os
import json
import numpy as np

# Configuration
STATS_FILE_PATH = "normalization_stats.json"

def load_normalization_stats(filepath):
    if not os.path.exists(filepath):
        raise FileNotFoundError(f"Normalization stats file not found at: {filepath}")
    with open(filepath, 'r') as f:
        return json.load(f)

def apply_normalization(X_seq, stats):
    """
    Applies static normalization parameters to the input tensor.
    Expects X_seq shape: (batch_size, sequence_length, 14)
    """
    X_norm = np.copy(X_seq)

    for key, s in stats["features"].items():
        ch = int(key.split("_")[0])

        # Skip vec[13] (Fallback) as it is dropped at the end
        if ch == 13:
            continue

        strategy = s["strategy"]
        col = X_norm[:, :, ch]

        if strategy == "log10_zscore":
            col = np.maximum(col, s["physical_floor"])
            col = np.log10(col)
            X_norm[:, :, ch] = (col - s["log10_mean"]) / s["log10_std"]

        elif strategy == "log1p_robust":
            col = np.log1p(np.maximum(col, 0.0))
            X_norm[:, :, ch] = (col - s["log1p_median"]) / s["log1p_iqr"]

        elif strategy == "zscore":
            X_norm[:, :, ch] = (col - s["mean"]) / s["std"]

        elif strategy == "clip_zscore":
            col = np.clip(col, -s["clip_bound_abs"], s["clip_bound_abs"])
            X_norm[:, :, ch] = (col - s["mean_post_clip"]) / s["std_post_clip"]

        elif strategy == "none":
            pass

    # Drop vec[13] (Fallback flag) -> new shape (batch_size, sequence_length, 13)
    X_norm = np.delete(X_norm, 13, axis=2)

    # Assert no invalid values generated during transform
    if np.isnan(X_norm).any() or np.isinf(X_norm).any():
        raise ValueError("Normalization produced NaN or Inf values.")

    return X_norm.astype(np.float32)

def process_inference_tensors(inference_tensors, stats_filepath=STATS_FILE_PATH):
    """
    Driver function to normalize a dictionary of active HARP tensors.
    inference_tensors format: {harpnum: (X_seq, X_static, X_mask)}
    """
    stats = load_normalization_stats(stats_filepath)
    normalized_tensors = {}

    for harp, (X_seq, X_static, X_mask) in inference_tensors.items():
        X_seq_norm = apply_normalization(X_seq, stats)
        normalized_tensors[harp] = (X_seq_norm, X_static, X_mask)

    return normalized_tensors

"""# Step 4: Inference"""

import os
import math
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

# Configuration
MODEL_PATH = "best_model.pt"
THRESHOLD = 0.75
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ==============================================================================
# 1. MODEL ARCHITECTURE
# ==============================================================================
class AthenaCTGRU(nn.Module):
    def __init__(
        self,
        input_dim: int = 13,
        hidden_dim: int = 128,
        static_dim: int = 3,
        mlp_dim1: int = 64,
        mlp_dim2: int = 32,
        dropout: float = 0.2,
    ):
        super().__init__()
        self.hidden_dim = hidden_dim
        self.decay_w = nn.Linear(1, hidden_dim)
        self.gru_cell = nn.GRUCell(input_dim, hidden_dim)

        self.mlp = nn.Sequential(
            nn.Linear(hidden_dim + static_dim, mlp_dim1),
            nn.GELU(),
            nn.Dropout(dropout),
            nn.Linear(mlp_dim1, mlp_dim2),
            nn.GELU(),
            nn.Linear(mlp_dim2, 2),
        )

    def forward(self, x_dyn, x_stat, x_mask):
        B, T, _ = x_dyn.shape
        dev = x_dyn.device

        h = torch.zeros(B, self.hidden_dim, device=dev)
        delta_t = torch.zeros(B, 1, device=dev)

        for t in range(T):
            x_t = x_dyn[:, t, :]
            m_t = x_mask[:, t, :]

            if t > 0:
                jolt_w = (m_t * x_mask[:, t - 1, :]).squeeze(-1)
            else:
                jolt_w = m_t.squeeze(-1)

            scale = torch.ones(B, 13, device=dev)
            scale[:, 11] = jolt_w
            x_t = x_t * scale

            delta_t = delta_t + 0.2

            decay_arg = F.relu(self.decay_w(delta_t))
            gamma = torch.exp(-decay_arg)
            h_decayed = h * gamma

            h_new = self.gru_cell(x_t, h_decayed)
            h = m_t * h_new + (1.0 - m_t) * h_decayed
            delta_t = delta_t * (1.0 - m_t)

        z = torch.cat([h, x_stat], dim=-1)
        return self.mlp(z)

# ==============================================================================
# 2. INFERENCE LOGIC
# ==============================================================================
def load_model(model_path, device):
    if not os.path.exists(model_path):
        raise FileNotFoundError(f"Model checkpoint not found at: {model_path}")

    model = AthenaCTGRU().to(device)
    # The training script saves state_dict directly to best_model.pt upon validation improvement
    model.load_state_dict(torch.load(model_path, map_location=device, weights_only=True))
    model.eval()
    return model

def prob_flare_within_T(T_hours: float, mu: float, sigma: float) -> float:
    if T_hours <= 0: return 0.0
    z = (math.log(T_hours) - mu) / sigma
    return 0.5 * (1.0 + math.erf(z / math.sqrt(2.0)))

def lognormal_quantile_approx(p: float, mu: float, sigma: float) -> float:
    z_scores = {0.25: -0.67449, 0.50: 0.0, 0.75: 0.67449, 0.10: -1.28155, 0.90: 1.28155}
    z = z_scores.get(p, 0.0)
    return math.exp(mu + sigma * z)

def predict_flares(normalized_tensors, model_path=MODEL_PATH, threshold=THRESHOLD):
    """
    Executes a forward pass on live active regions and computes robust metrics.
    """
    model = load_model(model_path, DEVICE)
    results = {}

    with torch.no_grad():
        for harp, (X_seq, X_static, X_mask) in normalized_tensors.items():

            x_dyn_t = torch.tensor(X_seq, dtype=torch.float32).to(DEVICE)
            x_stat_t = torch.tensor(X_static, dtype=torch.float32).to(DEVICE)
            x_mask_t = torch.tensor(X_mask, dtype=torch.float32).to(DEVICE)

            preds = model(x_dyn_t, x_stat_t, x_mask_t)
            mu_t = preds[:, 0:1]
            log_sigma_t = preds[:, 1:2]

            mu = float(mu_t.item())
            log_sigma = float(log_sigma_t.item())
            sigma = math.exp(log_sigma)

            # Compute Probabilities
            prob_24h = prob_flare_within_T(24.0, mu, sigma)
            is_flare = prob_24h >= threshold

            # Compute Median and IQR
            median_T = math.exp(mu)
            q1 = lognormal_quantile_approx(0.25, mu, sigma)
            q3 = lognormal_quantile_approx(0.75, mu, sigma)

            # Cumulative Probs
            cum_probs = {
                "1h": prob_flare_within_T(1.0, mu, sigma),
                "3h": prob_flare_within_T(3.0, mu, sigma),
                "6h": prob_flare_within_T(6.0, mu, sigma),
                "12h": prob_flare_within_T(12.0, mu, sigma),
                "24h": prob_24h,
                "36h": prob_flare_within_T(36.0, mu, sigma),
                "48h": prob_flare_within_T(48.0, mu, sigma),
            }

            results[harp] = {
                "probability_24h": prob_24h,
                "flagged": is_flare,
                "median_hours": median_T,
                "median_minutes": median_T * 60,
                "iqr_lower_hours": q1,
                "iqr_upper_hours": q3,
                "cumulative_probs": cum_probs,
                "mu": mu,
                "log_sigma": log_sigma,
                "sigma": sigma
            }

    return results

from datetime import datetime, timezone

import json

def format_and_output_results(inference_results, normalized_tensors):
    timestamp = datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S')
    print(f"\n[{timestamp} UTC] === INFERENCE RESULTS ===")

    if not inference_results:
        print("  No active regions passed criteria.")
        print("===========================================\n")
        return

    output_data = {
        "timestamp": timestamp,
        "history_hours": HISTORY_HOURS,
        "results": {}
    }

    for harp, result in inference_results.items():
        x_static = normalized_tensors[harp][1][0]
        hgc_x, hgc_y, cycle_phase = float(x_static[0]), float(x_static[1]), float(x_static[2])

        prob = float(result['probability_24h'])
        prediction = 1 if result['flagged'] else 0

        print(f"  HARPNUM {harp}:")
        print(f"    Flare Probability (<=24h) : {prob:.4f}")
        print(f"    Binary Prediction         : {prediction}")
        print(f"    HGC Position (Cos X, Y)   : {hgc_x:.4f}, {hgc_y:.4f}")
        print(f"    Solar Cycle Phase         : {cycle_phase:.4f}")

        output_data["results"][str(harp)] = {
            "probability_24h": prob,
            "flagged": bool(result['flagged']),
            "median_hours": float(result.get('median_hours', 0.0)),
            "median_minutes": float(result.get('median_minutes', 0.0)),
            "iqr_lower_hours": float(result.get('iqr_lower_hours', 0.0)),
            "iqr_upper_hours": float(result.get('iqr_upper_hours', 0.0)),
            "cumulative_probs": result.get('cumulative_probs', {}),
            "mu": float(result["mu"]),
            "log_sigma": float(result["log_sigma"]),
            "sigma": float(result.get("sigma", 0.0)),
            "hgc_x": hgc_x,
            "hgc_y": hgc_y,
            "cycle_phase": cycle_phase
        }

    print("===========================================\n")

    # ── Write per-window JSON — never clobbers other window sizes ──
    window_filename = f"predictions_{HISTORY_HOURS}h.json"
    with open(window_filename, "w") as f:
        json.dump(output_data, f, indent=4)
    print(f"Saved {HISTORY_HOURS}h window predictions to {window_filename}")

    # ── Always update live_predictions.json as the "most recently completed" run ──
    with open("live_predictions.json", "w") as f:
        json.dump(output_data, f, indent=4)
    print(f"Updated live_predictions.json (latest: {HISTORY_HOURS}h window @ {timestamp})")

    # Record to DB for the 30-day history chart
    all_probs = [float(r['probability_24h']) for r in inference_results.values()]
    global_score = max(all_probs) if all_probs else 0.0
    
    try:
        import requests
        requests.post("http://localhost:8000/api/predict/record", json={
            "results": output_data["results"],
            "global_score": global_score,
            "window_hours": HISTORY_HOURS,
        }, timeout=5)
        print("[SUCCESS] Recorded results to database history.")
    except Exception as e:
        print(f"[WARNING] Could not record to database (is uvicorn running?): {e}")

# Execute using the 'tensors' variable generated in Step 2
try:
    if 'tensors' in locals() and tensors:
        print("Applying normalization...")
        update_status("running", 90, "Applying z-score normalization...")
        norm_tensors = process_inference_tensors(tensors)

        print("Executing forward pass...")
        update_status("running", 95, "Running AthenaCTGRU PyTorch inference...")
        results = predict_flares(norm_tensors)

        format_and_output_results(results, norm_tensors)
        update_status("completed", 100, "Pipeline finished successfully.")
    else:
        print("Error: 'tensors' variable not found or empty. Rerun Step 2.")
        update_status("error", 0, "Pipeline failed: Extracted tensors empty.")
except Exception as e:
    import traceback
    print(f"Execution failed: {e}")
    update_status("error", 0, f"Pipeline failed: {str(e)}")
    traceback.print_exc()